# Замените YOUR_HOST на ваш реальный ВАШ_IP.sslip.io (напр. 203-0-113-10.sslip.io)
server {
    listen 80;
    server_name https://130.17.13.116.nip.io;

    # Нужно для certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name https://130.17.13.116.nip.io;

    ssl_certificate     /etc/letsencrypt/live/https://130.17.13.116.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/https://130.17.13.116.nip.io/privkey.pem;

    location / {
        proxy_pass http://bot:8443;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}